root: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
    - "yaml"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "prettier"
    - "plugin:yaml/recommended"
